frontend:
  build: ./frontend/.
  ports:
    - "8080:8080"
  volumes:
    - "./dist:/frontend"
  command: "npm start"
  environment:
    - NODE_ENV=development
    - LOG_LEVEL=info
backend:
  build: ./backend/.
  ports:
    - "3000:3000"
  volumes:
    - "./backend:/backend"
  command: "npm run dev"
  environment:
    - NODE_ENV=development
    - LOG_LEVEL=info
